<!-- top of layouts/scripts/layout.phtml -->
<?php 
$this->headMeta()->appendHttpEquiv(
	'Content-Type', 'text/html;charset=utf-8');
$this->headTitle('Todo List')->setSeparator(' - ');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css');

echo $this->doctype(); ?>  
<html> 
<head>
    <?php echo $this->headMeta(); ?> 
    <?php echo $this->headTitle(); ?> 
    <?php echo $this->headLink(); ?> 
</head>
<body>
<div id="header">
    <div id="logged-in-as"><?php echo $this->loggedInAs(); ?></div>
</div>
<div id="content">
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>
